name = "chat-state"
component_path = "/nix/store/6p3829k5x0k6x7y55gbilgq0vbm2lrpl-chat-state-0.1.0/lib/chat-state.wasm"
short_description = "Actor that manages state and behavior of conversations in the Claude Chat system"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]
