name = "chat-state"
component_path = "/nix/store/1q11vzmivz9f04138kz5m8frzpy2b8d5-chat-state-0.1.0/lib/component.wasm"
short_description = "Actor that manages state and behavior of conversations in the Claude Chat system"
init_state = "/Users/colinrozzi/work/actor-registry/chat-state/init.json"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]
