name = "chat-state"
version = "0.1.0"
component_path = "/Users/colinrozzi/work/actor-registry/chat-state/./target/wasm32-unknown-unknown/release/chat_state.wasm"
init_state = "/Users/colinrozzi/work/actor-registry/chat-state/init.json"

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]
