name = "chat-state"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/chat-state/./target/wasm32-unknown-unknown/release/chat_state.wasm"
init_state = "/Users/colinrozzi/work/actor-registry/chat-state/init.json"

[[handlers]]
type = "message-server"

[handlers.config]

[[handlers]]
type = "runtime"

[handlers.config]

[[handlers]]
type = "timing"

[handlers.config]
max_sleep_duration = 3600000
min_sleep_duration = 1

[[handlers]]
type = "supervisor"

[handlers.config]

[[handlers]]
type = "store"

[handlers.config]

[[handlers]]
type = "random"

[handlers.config]
max_bytes = 1048576
max_int = 9223372036854775807
allow_crypto_secure = false
